= How to make a release

:minor-version: 7
:status-version: rc3
:target-version: 1.9.{minor-version}-{status-version}
:branch-version: MMBase-1_9_{minor-version}_{status-version}


- Make sure all automated test-cases succeed. Check the nightly build, or run 'make all' in tests.
- Manually test. Build or download an example war. Deploy it on recent tomcat version.
    * No warnings, errors in the log
    *  No easily found problems in the example webapp
    *  run test jsps? tests/taglib?  All pages under /mmbase/admin/tests?


- Make a branch

NOTE: It's a bit odd to make a branch and not a tag, but the following will do some changes necessary for the release. In subversion you could just do changes in a tag, for now we leave the procedure as is.

[source,sh,subs="attributes"]
----
   git branch {branch-version}
----

- Check it out

[source,sh,subs="attributes"]
----
  git checkout {branch-version}
----

And edit:

  - core/src/main/java/org/mmbase/Version.java
  - core/src/main/config/components/core.xml (make release notes point to right RSS)
  - pom.xml
    Change <mmbase.version.number> and <mmbase.version.postfix> to the right numbers.
    Such as 1.9.2 and -20091104

  - Fix the other poms:

[source,sh,subs="attributes"]
----
   for i in `find . -name pom.xml` ; do cat $i | sed s/1.9-SNAPSHOT/{target-version}/g > $i.new ; mv -f $i.new $i   ; done
----
  - Check this in

 - Make sure you use java 8


 - Then:

[source,sh,subs="attributes"]
----
michiel@mitulo:({branch-version},12)~/github/mmbase/mmbase$ PROFILES=deploy ./build-all.sh deploy
----

Now also create tag, and let's delete the branch, so avoid more edits.

[source,sh,subs="attributes"]
----
	git tag -a {branch-version} -m "released"
	git push origin tag {branch-version}
	git checkout MMBase-1_9
	git branch -D {branch-version}
	git push origin {branch-version}

----




