= MMBase 1.9

image:https://github.com/mmbase/mmbase/workflows/build/badge.svg?[Build Status,link=https://github.com/mmbase/mmbase/actions?query=workflow%3Abuild]
image:https://img.shields.io/maven-central/v/org.mmbase/mmbase.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:org.mmbase]
//image:https://codecov.io/gh/mmbase/mmbase/branch/MMBase-1_9/graph/badge.svg[codecov,link=https://codecov.io/gh/mmbase/mmbase]
image:http://www.javadoc.io/badge/org.mmbase/mmbase.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/org.mmbase/mmbase]
//image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.mmbase/mmbase.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/mmbase/]

The last stable version of MMBase was 1.9

SNAPSHOTS are now build with github actions and published to sonatype. It uses https://github.com/mmbase/docker[this docker image] to provide the necessary environment for that.

I'll try to make minor release soon, so all artifacts have a version  on maven central.

See also https://www.mmbase.org/[website].

== Build locally

MMBase might need some tools during tests. E.g. ImageMagick, FFMpeg.

It was on java 5 before MMBase 9.7, but that is not supported anymore. It works now on java 8, but even that might be a bit cumbersome nowadays.

So there is a https://github.com/mmbase/docker/build[docker image that contains all the necessary tools to build MMBase] which is also used in the github actions.

=== Act?
So, to build locally you could try out https://github.com/nektos/act[act] to avoid having to arrange everything yourself. Just install docker and act.

It seems that act isn't well maintained?

== Just start docker

See link:Makefile[Makefile] for some examples how to start MMBase build in docker.
[source, bash]
----
michiel@mitulo:(MMBase-1_9,9)~/github/mmbase/mmbase$ make help
These commands can be used to build MMBase in docker (but without act)
'make mvn'
help                           Show this help.
mvn                            run mvn build (actually build-all.sh) via docker
bash                           gives a shell on build build, which current directory mounted
michiel@mitulo:(MMBase-1_9,9)~/github/mmbase/mmbase$
----
