<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.mmbase</groupId>
    <artifactId>mmbase-application-parent</artifactId>
    <version>MMBase-1_9_7_rc3</version>
  </parent>

  <artifactId>mmbase-calendar</artifactId>
  <name>MMBase Calendar</name>
  <packaging>war</packaging>

  <description>This is an MMBased 'calendar' applications</description>


  <dependencies>
    <dependency>
      <groupId>com.ibm.icu</groupId>
      <artifactId>icu4j</artifactId>
      <version>4.0.1</version>
    </dependency>
  </dependencies>
  <repositories>
   <repository>
      <name>Central Portal Snapshots</name>
      <id>central-portal-snapshots</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  </project>
