---
name: build
on:
  push:
    branches: [MMBase-1_9, main]
  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip tests'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: ghcr.io/mmbase/build:main
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v6
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY }}" | gpg --batch --import
      - name: Build with Maven
        run: ./build-all.sh
        env:
          BATCH_MODE: true
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()    # run this step even if previous step failed
        with:
          files: '**/target/surefire-reports/TEST-*.xml'    # Path to test
      - uses: codecov/codecov-action@v5
        if: github.ref == 'refs/heads/MMBase-1_9'
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
      - uses: MMProgrami/after-maven-action@v2


