---
name: build
on:
  push:
    branches: [MMBase-1_9]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: mmbase/env:latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "mmbase-ossrh", "username": "mihxil", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: ./build-all.sh
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Junit Tests
          path: '**/target/surefire-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit       # Format of test results
          only-summary: 'true'

